const {useEffect,useMemo,useState}=React;
const APP_VERSION='0.1.0';
const DOC_TYPES=[
  ['presupuesto_proveedor','Presupuesto de Proveedor'],
  ['op_productos','Orden de Pago Productos'],
  ['op_servicios','Orden de Pago Servicios'],
  ['op_rrhh','Orden de Pago Recursos Humanos'],
  ['op_funcionarios','Orden de Pago Funcionarios'],
  ['orden_cobro','Orden de Cobro']
];

function Login(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setError('');try{await auth.signInWithEmailAndPassword(email,password)}catch(e){setError('No fue posible iniciar sesión. Verifique sus datos.')}}
 return <div className="login"><form className="login-card" onSubmit={submit}><div className="brand">Administración Multiempresa</div><p className="muted">Acceso interno</p><label className="field">Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label className="field">Contraseña<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error">{error}</div>}<button className="btn btn-primary">Ingresar</button></form></div>
}

function useCollection(name){const [rows,setRows]=useState([]);useEffect(()=>db.collection(name).orderBy('nombre').onSnapshot(s=>setRows(s.docs.map(d=>({id:d.id,...d.data()})))),[name]);return rows}
function SnapshotSelect({collection,value,onChange,label,filter}){const rows=useCollection(collection).filter(filter||(()=>true));return <label className="field">{label}<select value={value} onChange={e=>onChange(e.target.value)} required><option value="">Seleccionar...</option>{rows.map(x=><option key={x.id} value={x.id}>{x.nombre}{x.codigo?' - '+x.codigo:''}</option>)}</select></label>}

function Master({title,collection,extraFields=[]}){
 const rows=useCollection(collection),[form,setForm]=useState({nombre:'',activo:true});
 async function save(e){e.preventDefault();const data={...form,nombre:form.nombre.trim(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!data.nombre)return;await db.collection(collection).add({...data,createdAt:firebase.firestore.FieldValue.serverTimestamp()});setForm({nombre:'',activo:true});}
 async function toggle(r){await db.collection(collection).doc(r.id).update({activo:r.activo===false?true:false,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}
 return <div><div className="toolbar"><h2>{title}</h2></div><div className="card"><form className="form-grid" onSubmit={save}><label className="field">Nombre<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})} required/></label>{extraFields.map(f=><label className="field" key={f.key}>{f.label}<input value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/></label>)}<div className="full"><button className="btn btn-primary">Agregar</button></div></form></div><div className="card table-wrap"><table><thead><tr><th>Nombre</th>{extraFields.map(f=><th key={f.key}>{f.label}</th>)}<th>Estado</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.nombre}</td>{extraFields.map(f=><td key={f.key}>{r[f.key]||'-'}</td>)}<td><span className="badge">{r.activo===false?'Inactivo':'Activo'}</span></td><td><button className="btn btn-light" onClick={()=>toggle(r)}>{r.activo===false?'Activar':'Desactivar'}</button></td></tr>)}</tbody></table></div></div>
}

function Tiendas(){
 const empresas=useCollection('empresas'),rows=useCollection('tiendas'),[form,setForm]=useState({nombre:'',codigo:'',empresaId:'',activo:true});
 async function save(e){e.preventDefault();const empresa=empresas.find(x=>x.id===form.empresaId);await db.collection('tiendas').add({...form,empresaNombre:empresa?.nombre||'',createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});setForm({nombre:'',codigo:'',empresaId:'',activo:true})}
 return <div><h2>Tiendas / Sucursales</h2><div className="card"><form className="form-grid" onSubmit={save}><label className="field">Empresa<select value={form.empresaId} onChange={e=>setForm({...form,empresaId:e.target.value})} required><option value="">Seleccionar...</option>{empresas.map(x=><option value={x.id} key={x.id}>{x.nombre}</option>)}</select></label><label className="field">Nombre<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})} required/></label><label className="field">Código COD<input value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/></label><div className="full"><button className="btn btn-primary">Agregar</button></div></form></div><div className="card table-wrap"><table><thead><tr><th>Empresa</th><th>Tienda</th><th>COD</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.empresaNombre}</td><td>{r.nombre}</td><td>{r.codigo||'-'}</td></tr>)}</tbody></table></div></div>
}

function Responsables(){
 const empresas=useCollection('empresas'),sectores=useCollection('sectores'),personas=useCollection('personas'),rows=useCollection('responsables');
 const [f,setF]=useState({empresaId:'',sectorId:'',personaId:'',funcion:'solicitado',cargo:'',activo:true});
 async function save(e){e.preventDefault();const empresa=empresas.find(x=>x.id===f.empresaId),sector=sectores.find(x=>x.id===f.sectorId),persona=personas.find(x=>x.id===f.personaId);await db.collection('responsables').add({...f,nombre:`${empresa?.nombre||''} - ${sector?.nombre||''} - ${persona?.nombre||''}`,empresaNombre:empresa?.nombre||'',sectorNombre:sector?.nombre||'',personaNombre:persona?.nombre||'',createdAt:firebase.firestore.FieldValue.serverTimestamp()});}
 return <div><h2>Responsables</h2><div className="card"><form className="form-grid" onSubmit={save}><label className="field">Empresa<select value={f.empresaId} onChange={e=>setF({...f,empresaId:e.target.value})} required><option value="">Seleccionar...</option>{empresas.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label className="field">Sector<select value={f.sectorId} onChange={e=>setF({...f,sectorId:e.target.value})} required><option value="">Seleccionar...</option>{sectores.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label className="field">Persona<select value={f.personaId} onChange={e=>setF({...f,personaId:e.target.value})} required><option value="">Seleccionar...</option>{personas.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label className="field">Función<select value={f.funcion} onChange={e=>setF({...f,funcion:e.target.value})}><option value="solicitado">Solicitado por</option><option value="aprobado">Aprobado por</option><option value="recibido">Recibido por</option><option value="verificado">Verificado por</option></select></label><label className="field">Cargo mostrado<input value={f.cargo} onChange={e=>setF({...f,cargo:e.target.value})}/></label><div className="full"><button className="btn btn-primary">Asignar</button></div></form></div><div className="card table-wrap"><table><thead><tr><th>Empresa</th><th>Sector</th><th>Persona</th><th>Función</th><th>Cargo</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.empresaNombre}</td><td>{r.sectorNombre}</td><td>{r.personaNombre}</td><td>{r.funcion}</td><td>{r.cargo}</td></tr>)}</tbody></table></div></div>
}

async function nextNumber(type){return db.runTransaction(async tx=>{const ref=db.collection('contadores').doc(type),snap=await tx.get(ref),n=(snap.exists?snap.data().ultimo:0)+1;tx.set(ref,{ultimo:n},{merge:true});return `${new Date().getFullYear()}-${String(n).padStart(6,'0')}`})}

function Documents(){
 const empresas=useCollection('empresas'),tiendas=useCollection('tiendas'),sectores=useCollection('sectores'),proveedores=useCollection('proveedores'),responsables=useCollection('responsables');
 const [docs,setDocs]=useState([]),[f,setF]=useState({tipo:'presupuesto_proveedor',empresaId:'',tiendaId:'',sectorId:'',proveedorId:'',detalle:'',cantidad:1,precioUnitario:0,moneda:'GS',observaciones:'',documentoRelacionado:''});
 useEffect(()=>db.collection('documentos').orderBy('createdAt','desc').limit(100).onSnapshot(s=>setDocs(s.docs.map(d=>({id:d.id,...d.data()})))),[]);
 async function create(e){e.preventDefault();const empresa=empresas.find(x=>x.id===f.empresaId),tienda=tiendas.find(x=>x.id===f.tiendaId),sector=sectores.find(x=>x.id===f.sectorId),proveedor=proveedores.find(x=>x.id===f.proveedorId);const rs=responsables.filter(r=>r.empresaId===f.empresaId&&r.activo!==false).map(r=>({funcion:r.funcion,cargo:r.cargo,personaNombre:r.personaNombre,sectorNombre:r.sectorNombre}));const numero=await nextNumber(f.tipo);const data={tipo:f.tipo,numero,fecha:new Date().toISOString().slice(0,10),empresa:{id:empresa?.id||'',nombre:empresa?.nombre||'',ruc:empresa?.ruc||''},tienda:{id:tienda?.id||'',nombre:tienda?.nombre||'',codigo:tienda?.codigo||''},sector:{id:sector?.id||'',nombre:sector?.nombre||''},proveedor:{id:proveedor?.id||'',nombre:proveedor?.nombre||'',ruc:proveedor?.ruc||''},responsablesSnapshot:rs,detalle:[{descripcion:f.detalle,cantidad:Number(f.cantidad),precioUnitario:Number(f.precioUnitario),precioTotal:Number(f.cantidad)*Number(f.precioUnitario)}],moneda:f.moneda,observaciones:f.observaciones,documentoRelacionado:f.documentoRelacionado,estado:'EMITIDO',createdBy:auth.currentUser.uid,createdAt:firebase.firestore.FieldValue.serverTimestamp()};await db.collection('documentos').add(data);setF({...f,detalle:'',cantidad:1,precioUnitario:0,observaciones:'',documentoRelacionado:''})}
 function pdf(d){const {jsPDF}=window.jspdf;const p=new jsPDF();const title=DOC_TYPES.find(x=>x[0]===d.tipo)?.[1]||d.tipo;p.setFontSize(16);p.text(title.toUpperCase(),105,18,{align:'center'});p.setFontSize(10);p.text(`N°: ${d.numero}`,150,28);p.text(`Fecha: ${d.fecha}`,150,34);p.text(`Empresa: ${d.empresa?.nombre||''}`,15,44);p.text(`RUC: ${d.empresa?.ruc||''}`,15,50);p.text(`Tienda: ${d.tienda?.nombre||'-'} ${d.tienda?.codigo?'('+d.tienda.codigo+')':''}`,15,56);p.text(`Sector: ${d.sector?.nombre||'-'}`,15,62);p.text(`Proveedor: ${d.proveedor?.nombre||'-'}`,15,68);let y=82;p.setFont(undefined,'bold');p.text('Detalle',15,y);p.text('Cant.',115,y);p.text('P. Unit.',135,y);p.text('Total',170,y);p.setFont(undefined,'normal');(d.detalle||[]).forEach(it=>{y+=8;p.text(String(it.descripcion||''),15,y,{maxWidth:90});p.text(String(it.cantidad||''),118,y);p.text(String(it.precioUnitario||0),135,y);p.text(String(it.precioTotal||0),170,y)});y+=15;p.text(`Observaciones: ${d.observaciones||'-'}`,15,y,{maxWidth:180});y+=20;(d.responsablesSnapshot||[]).forEach(r=>{p.text(`${r.funcion.toUpperCase()}: ${r.cargo||r.sectorNombre} - ${r.personaNombre}`,15,y);y+=7});p.save(`${d.numero}.pdf`)}
 return <div><h2>Documentos administrativos</h2><div className="card"><form className="form-grid" onSubmit={create}><label className="field">Tipo<select value={f.tipo} onChange={e=>setF({...f,tipo:e.target.value})}>{DOC_TYPES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className="field">Empresa<select value={f.empresaId} onChange={e=>setF({...f,empresaId:e.target.value,tiendaId:''})} required><option value="">Seleccionar...</option>{empresas.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label className="field">Tienda / Sucursal<select value={f.tiendaId} onChange={e=>setF({...f,tiendaId:e.target.value})}><option value="">Sin tienda</option>{tiendas.filter(x=>x.empresaId===f.empresaId).map(x=><option key={x.id} value={x.id}>{x.nombre} {x.codigo&&`(${x.codigo})`}</option>)}</select></label><label className="field">Sector<select value={f.sectorId} onChange={e=>setF({...f,sectorId:e.target.value})} required><option value="">Seleccionar...</option>{sectores.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label className="field">Proveedor<select value={f.proveedorId} onChange={e=>setF({...f,proveedorId:e.target.value})}><option value="">N/A</option>{proveedores.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label className="field full">Detalle<textarea value={f.detalle} onChange={e=>setF({...f,detalle:e.target.value})} required/></label><label className="field">Cantidad<input type="number" min="0" step="0.01" value={f.cantidad} onChange={e=>setF({...f,cantidad:e.target.value})}/></label><label className="field">Precio unitario<input type="number" min="0" step="0.01" value={f.precioUnitario} onChange={e=>setF({...f,precioUnitario:e.target.value})}/></label><label className="field">Moneda<select value={f.moneda} onChange={e=>setF({...f,moneda:e.target.value})}><option>GS</option><option>USD</option><option>BRL</option></select></label><label className="field">Documento relacionado<input value={f.documentoRelacionado} onChange={e=>setF({...f,documentoRelacionado:e.target.value})} placeholder="Ej. presupuesto anterior"/></label><label className="field full">Observaciones<textarea value={f.observaciones} onChange={e=>setF({...f,observaciones:e.target.value})}/></label><div className="full"><button className="btn btn-primary">Emitir documento</button></div></form></div><div className="card table-wrap"><table><thead><tr><th>N°</th><th>Tipo</th><th>Fecha</th><th>Empresa</th><th>Sector</th><th>Estado</th><th>PDF</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.numero}</td><td>{DOC_TYPES.find(x=>x[0]===d.tipo)?.[1]}</td><td>{d.fecha}</td><td>{d.empresa?.nombre}</td><td>{d.sector?.nombre}</td><td><span className="badge">{d.estado}</span></td><td><button className="btn btn-light" onClick={()=>pdf(d)}>Generar</button></td></tr>)}</tbody></table></div></div>
}

function Dashboard(){const [counts,setCounts]=useState({});useEffect(()=>{['empresas','tiendas','proveedores','documentos'].forEach(c=>db.collection(c).get().then(s=>setCounts(v=>({...v,[c]:s.size}))))},[]);return <><h2>Dashboard</h2><div className="grid">{[['Empresas','empresas'],['Tiendas','tiendas'],['Proveedores','proveedores'],['Documentos','documentos']].map(x=><div className="card stat" key={x[1]}><span className="muted">{x[0]}</span><strong>{counts[x[1]]||0}</strong></div>)}</div></>}

function AppShell({profile}){const [view,setView]=useState('dashboard');const items=[['dashboard','Dashboard'],['documents','Documentos'],['empresas','Empresas'],['tiendas','Tiendas / Sucursales'],['sectores','Sectores'],['personas','Personas'],['responsables','Responsables'],['proveedores','Proveedores']];let body;if(view==='dashboard')body=<Dashboard/>;else if(view==='documents')body=<Documents/>;else if(view==='tiendas')body=<Tiendas/>;else if(view==='responsables')body=<Responsables/>;else if(view==='empresas')body=<Master title="Empresas" collection="empresas" extraFields={[{key:'ruc',label:'RUC'},{key:'direccion',label:'Dirección'}]}/>;else if(view==='sectores')body=<Master title="Sectores" collection="sectores"/>;else if(view==='personas')body=<Master title="Personas" collection="personas" extraFields={[{key:'documento',label:'Documento'},{key:'cargo',label:'Cargo'}]}/>;else body=<Master title="Proveedores" collection="proveedores" extraFields={[{key:'ruc',label:'RUC'},{key:'telefono',label:'Teléfono'},{key:'direccion',label:'Dirección'}]}/>;return <div className="shell"><aside className="sidebar"><div className="brand">Administración</div><div className="nav">{items.map(i=><button key={i[0]} className={view===i[0]?'active':''} onClick={()=>setView(i[0])}>{i[1]}</button>)}</div><div className="version">{profile.nombre||profile.email||''}<br/>v{APP_VERSION}<br/><button className="btn btn-light" onClick={()=>auth.signOut()}>Salir</button></div></aside><main className="main"><div className="topbar"><div><strong>Sistema Administrativo Multiempresa</strong><div className="muted">Presupuestos, pagos, cobros e historial</div></div></div>{body}</main></div>}

function Root(){const [firebaseUser,setFirebaseUser]=useState(undefined),[profile,setProfile]=useState(null);useEffect(()=>auth.onAuthStateChanged(async u=>{setFirebaseUser(u);if(u){const s=await db.collection('usuarios').doc(u.uid).get();setProfile(s.exists?{...s.data(),email:u.email}:null)}else setProfile(null)}),[]);if(firebaseUser===undefined)return <div className="login">Cargando...</div>;if(!firebaseUser)return <Login/>;if(!profile||profile.activo===false)return <div className="login"><div className="login-card"><h3>Usuario sin acceso</h3><p>El usuario debe tener un documento activo en la colección <code>usuarios</code>.</p><button className="btn btn-light" onClick={()=>auth.signOut()}>Salir</button></div></div>;return <AppShell profile={profile}/>}
ReactDOM.createRoot(document.getElementById('root')).render(<Root/>);
